-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, round(C.DAILY_FEE * 30 * (100-CP.DISCOUNT_RATE)/100) as FEE
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
     ON C.CAR_TYPE = CP.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE START_DATE < '2022-12-01 00:00:00'
                             AND
                             END_DATE >= '2022-11-01 00:00:00')
AND
C.CAR_TYPE in ('세단', 'SUV')
AND
CP.DURATION_TYPE = '30일 이상'
AND
C.DAILY_FEE * 30 * (100-CP.DISCOUNT_RATE)/100 BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC







# select *
# from CAR_RENTAL_COMPANY_DISCOUNT_PLAN

